name: Webhook

# Only trigger, when the API File Format workflow succeeds
on:
  workflow_run:
    workflows: ["MegaLinter"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Webhook
        uses: distributhor/workflow-webhook@v2.0.3
        env:
         webhook_type: 'json-extended'
         webhook_url: ${{ secrets.WEBHOOK_URL }}
         webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
